In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [19]:
df.bedrooms.mean()

4.2

In [26]:

df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [32]:
features = df[["area", "bedrooms", "age"]]
labels = df.price

In [33]:
model = LinearRegression()
model.fit(features, labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [35]:
model.intercept_

221323.00186540443

In [36]:
model.predict([[3000, 3, 40]])

array([498408.25158031])

In [37]:

112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

In [38]:
model.predict([[2500, 4, 5]])

array([578876.03748933])